name: rfw_builder
description: |
  A builder tool to generate RemoteFlutterWidget tree;
  converting between .rfw and .rfwtxt formats, including the intermediate class RemoteWidgetLibrary.
version: 0.0.3+5
repository: https://github.com/ebwood/rfwt

environment:
  sdk: ^3.2.0

executables: 
  rfw2txt:
  txt2rfw:

dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  path: ^1.9.0
  rfw: ^1.0.25
  yaml: ^3.1.2

dev_dependencies:
  import_sorter: ^4.6.0
  lints: ^3.0.0
  test: ^1.24.0
