name: rfw_builder
description: |
  A builder tool to generate RemoteFlutterWidget tree
version: 0.0.1
repository: https://github.com/ebwood/rfwt

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  rfw: ^1.0.25

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
