name: rfwt

packages:
  - packages/rfw_builder
  - packages/widget2rfw

scripts:
  add_sort:
    exec: dart pub add --dev import_sorter
  push:
    run: melos run analyze && git push
  import_sort:
    exec: dart run import_sorter:main --no-comments
  analyze:
    exec: melos run import_sort && dart analyze
  analyze_server:
    exec: dart analyze
  test:
    exec: dart test
  # use bin/change_version command to update every package version const variable in bin/version.dart if provided
  update_version:
    exec: change_version

command:
  version:
    hooks:
      pre: melos clean && melos bootstrap && melos run analyze && melos run test
      preCommit: melos update_version
      # post: melos change_version