name: rfwt

packages:
  - packages/txt2rfw
  - packages/rfw2txt
  - packages/widget2rfw
  - packages/rfw_builder
  - packages/rfw_txt

scripts:
  add_sort:
    exec: dart pub add --dev import_sorter
  push:
    run: melos run analyze && git push
  import_sort:
    exec: dart run import_sorter:main --no-comments
  analyze:
    exec: melos run import_sort && dart analyze
  test:
    exec: dart test

command:
  version:
    hooks:
      pre: melos clean && melos bootstrap && melos run analyze && melos run test