name: rfwt

packages:
  - packages/txt2rfw
  - packages/rfw2txt
  - packages/widget2rfw
  - packages/rfw_builder

scripts:
  analyze:
    exec: dart analyze
  test:
    exec: dart test

command:
  version:
    hooks:
      pre: melos clean && melos bootstrap && melos run analyze && melos run test