name: widget2rfw
description: |
  convert flutter widget to .rfw file.
version: 0.0.1
homepage: https://github.com/ebwood/rfwt

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: '>=3.16.0'

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  rfw: ^1.0.26

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
  test: ^1.24.9
