name: widget2rfw
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/ebwood/rfwt

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  rfw: ^1.0.26

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0

