name: txt2rfw
description: >
  A tool to parse RemoteFlutterWidget .rfwtxt format to .rfw format.
version: 0.0.6
repository: https://github.com/ebwood/rfwt

environment:
  sdk: ^3.3.0
  flutter: '>=3.10.0 <4.0.0'

executables: 
  txt2rfw:

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  path: ^1.9.0
  rfw: ^1.0.24
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0