name: txt2rfw
description: convert .rfwtxt to .rfw
version: 0.0.1
repository: https://github.com/ebwood/rfwt/packages/txt2rfw

environment:
  sdk: ^3.3.0

executables: 
  txt2rfw:

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  path: ^1.9.0
  rfw: ^1.0.24
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
