name: rfw_tools
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

executables: 
  rfw2txt:
  txt2rfw:

# Add regular dependencies here.
dependencies:
  args: ^2.4.2

dev_dependencies:
  import_sorter: ^4.6.0
  lints: ^3.0.0
  test: ^1.24.0
