name: rfw_txt
description: |
  A tool for converting between .rfw and .rfwtxt formats, including the intermediate class RemoteWidgetLibrary.
version: 0.0.1
repository: https://github.com/ebwood/rfwt

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  path: ^1.9.0
  rfw: ^1.0.26
  yaml: ^3.1.2

dev_dependencies:
  import_sorter: ^4.6.0
  lints: ^3.0.0
  test: ^1.24.0
