name: rfw2txt
description: >
  Parse RemoteFlutterWidget .rfw format to .rfwtxt format.
version: 0.0.4
repository: https://github.com/ebwood/rfwt/tree/main/packages/rfw2txt

environment:
  sdk: ^3.3.0
  flutter: '>=3.10.0 <4.0.0'

executables: 
  rfw2txt:

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  path: ^1.9.0
  rfw: ^1.0.25
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
