name: rfw2txt
description: convert .rfw to .rfwtxt
version: 0.0.1
repository: https://github.com/ebwood/rfwt/packages/rfw2txt

environment:
  sdk: ^3.3.0

executables: 
  rfw2txt:

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  path: ^1.9.0
  rfw: ^1.0.24

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
